Update Jetstream, add optional sampler args.
google/jetstream-pytorch pull request #178
Opened 2024-08-30 23:17 UTC by qihqi

2024-09-03 03:06 UTC, lsy323 approved these changes

2024-09-03 17:14 UTC, wang2yn84 requested changes
In general good, some nits and small issues. Thank you!

2024-09-03 17:14 UTC, wang2yn84 commented on jetstream_pt/fetch_models.py
>    num_heads: int
This is actually number of kv heads.

2024-09-04 03:32 UTC, FanhaiLu1 approved these changes

2024-09-06 16:36 UTC, qihqi commented on README.md
> +Weights downloaded from HuggingFace will be stored by default in `checkpoints` folder.
For gs bucket it need to be brought locally or use mount using Fuse.

The working dir can be edited. Added paragraph to describe that.

2024-09-06 16:37 UTC, qihqi commented on jetstream_pt/fetch_models.py
>    num_heads: int
renamed var

2024-09-10 00:26 UTC, wang2yn84 commented on README.md
> +Weights downloaded from HuggingFace will be stored by default in `checkpoints` folder.
It'll be great if you can add how to change the working dir. Cuz for us, we also need to direct to the external ssd. I will approve the PR to unblock you for now.

2024-09-10 00:26 UTC, wang2yn84 approved these changes

2024-09-10 02:57 UTC, merged